name: Deploy to EAS Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy web app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Setup Expo & EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Export web app
        run: npx expo export --platform web

      - name: Deploy to EAS Hosting
        run: eas deploy --non-interactive
